#
# Copyright (c) 1996, 1997 The University of Utah and
# the Computer Systems Laboratory at the University of Utah (CSL).
#
# This file is part of Flick, the Flexible IDL Compiler Kit.
#
# Flick is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Flick is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Flick; see the file COPYING.  If not, write to
# the Free Software Foundation, 59 Temple Place #330, Boston, MA 02111, USA.
#

ifndef _flick_makerules_test_fe_
_flick_makerules_test_fe_ = yes

# Any Makefile that includes this file is expected to define the following
# macros:
#
# `TESTS', the set of tests.  These names do *not* have extensions; the rules
# in this file know how to add extensions as needed to construct input and
# output file names.

###############################################################################

# `ARCHETYPE_EXTS' describes which files may be saved for later reference (see
# the file `test/GNUmakerules.common' for more information).  For Flick front
# ends, we want to save the generated AOI files.

ARCHETYPE_EXTS = .aoi

include $(SRCDIR)/test/GNUmakerules.common

###############################################################################
###############################################################################
####
#### Here are the rules for generating AOI (and `.aod') files from IDL inputs.
####
###############################################################################
###############################################################################

.PHONY: all all-aoi all-aod

all: all-aoi

all-aoi: $(addsuffix .aoi,$(TESTS))

all-aod: $(addsuffix .aod,$(TESTS))

.PHONY: $(TESTS)

$(TESTS): %: %.aoi

###

%.aoi: %.idl $(FLICK_FE_CORBA)
	$(FLICK_FE_CORBA) $(FLICK_FE_FLAGS) -o $@ $< 

%.aoi: %.x $(FLICK_FE_SUN)
	$(FLICK_FE_SUN) $(FLICK_FE_FLAGS) -o $@ $<

# Bogus rule for MIG, which doesn't result in valid `.aoi' files.
%.aoi: %.defs
	touch $@

%.aod: %.aoi $(AOID)
	$(AOID) $(AOID_FLAGS) $<

###############################################################################
###############################################################################
####
#### Here are the housecleaning rules.
####
###############################################################################
###############################################################################

CLEAN_FILES += $(addsuffix .aoi,$(TESTS)) \
	       $(addsuffix .aod,$(TESTS))

# NOTE that `GNUmakerules.common' declares the `<test>.clean' targets as phony.

$(addsuffix .clean,$(TESTS)): %.clean:
	$(RM) $*.aoi $*.aod

endif

## End of file.

