#
# Copyright (c) 1996 The University of Utah and
# the Computer Systems Laboratory at the University of Utah (CSL).
#
# This file is part of Flick, the Flexible IDL Compiler Kit.
#
# Flick is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Flick is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Flick; see the file COPYING.  If not, write to
# the Free Software Foundation, 59 Temple Place #330, Boston, MA 02111, USA.
#

# makefile -- example

CFLAGS=-DRPCGEN
SVROBJ=pwsrv.o pw_svc.o pw_xdr.o
CLNOBJ=pwcln.o pw_clnt.o pw_xdr.o
#for Solaris ...
#LDLIBS=-lnsl

all:	pw.h pwsrv-sun pwcln-sun

clean:
	rm -f pwsrv pwcln $(SVROBJ) $(CLNOBJ) 
	rm -f pw_clnt.c pw_svc.c pw_xdr.c pw.h

pw_xdr.c: pw.x
	rpcgen -c -o $@ pw.x 

pw.h: pw.x
	rpcgen -h -o $@ pw.x 

pw_svc.c: pw.x
	rpcgen -s udp -o $@ pw.x 

pw_clnt.c: pw.x
	rpcgen -l -o $@ pw.x 

pwsrv-sun: $(SVROBJ)
	cc -o $@ $(SVROBJ) $(LDLIBS)

pwcln-sun: $(CLNOBJ)
	cc -o $@ $(CLNOBJ) $(LDLIBS)
