#include <mom/meta.h>
/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <rpc/rpc.h>

bool_t
xdr_io_file_index(xdrs, objp)
	register XDR *xdrs;
	io_file_index *objp;
{

	if (!xdr_int(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_io_file(xdrs, objp)
	register XDR *xdrs;
	io_file *objp;
{

	if (!xdr_string(xdrs, &objp->id, ~0))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->flags))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->references))
		return (FALSE);
	if (!xdr_array(xdrs, (char **)&objp->includes.includes_val, (u_int *) &objp->includes.includes_len, ~0,
		sizeof (io_file_index), (xdrproc_t) xdr_io_file_index))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_io_file_mask(xdrs, objp)
	register XDR *xdrs;
	io_file_mask *objp;
{

	if (!xdr_u_int(xdrs, &objp->mask_flags))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->id, ~0))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->set_flags))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->unset_flags))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_data_channel_index(xdrs, objp)
	register XDR *xdrs;
	data_channel_index *objp;
{

	if (!xdr_int(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_data_channel(xdrs, objp)
	register XDR *xdrs;
	data_channel *objp;
{

	if (!xdr_io_file_index(xdrs, &objp->input))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->id, ~0))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->flags))
		return (FALSE);
	if (!xdr_array(xdrs, (char **)&objp->outputs.outputs_val, (u_int *) &objp->outputs.outputs_len, ~0,
		sizeof (io_file_index), (xdrproc_t) xdr_io_file_index))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_data_channel_mask(xdrs, objp)
	register XDR *xdrs;
	data_channel_mask *objp;
{

	if (!xdr_u_int(xdrs, &objp->mask_flags))
		return (FALSE);
	if (!xdr_pointer(xdrs, (char **)&objp->input, sizeof (io_file_mask), (xdrproc_t) xdr_io_file_mask))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->id, ~0))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->set_flags))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->unset_flags))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_meta(xdrs, objp)
	register XDR *xdrs;
	meta *objp;
{

	if (!xdr_array(xdrs, (char **)&objp->files.files_val, (u_int *) &objp->files.files_len, ~0,
		sizeof (io_file), (xdrproc_t) xdr_io_file))
		return (FALSE);
	if (!xdr_array(xdrs, (char **)&objp->channels.channels_val, (u_int *) &objp->channels.channels_len, ~0,
		sizeof (data_channel), (xdrproc_t) xdr_data_channel))
		return (FALSE);
	return (TRUE);
}
